```{r}
#Descargar datos de:
"https://www.kaggle.com/datasets/arashnic/fitbit/data?select=mturkfitbit_export_4.12.16-5.12.16"

#Definir ruta de acceso
setwd() #agregar aquí la ruta de acceso de la carpeta del link anterior
```


```{r}
#cargar los archivos
actividad_diaria <- read.csv("dailyActivity_merged.csv")
peso_eventual <- read.csv("weightLogInfo_merged.csv")
sueno_diario <- read.csv("sleepDay_merged.csv")
rc_segundos <- read.csv("heartrate_seconds_merged.csv")
```

```{r}
#mantener un mismo formato de fecha
actividad_diaria$Date <-format(as.Date(actividad_diaria$ActivityDate, format = "%m/%d/%Y"), "%Y-%m-%d")
sueno_diario$Date <- format(as.Date(sueno_diario$SleepDay, format = "%m/%d/%Y"), "%Y-%m-%d")
peso_eventual$Date <- format(as.Date(peso_eventual$Date, format = "%m/%d/%Y"), "%Y-%m-%d")
rc_segundos$Time <- format(as.POSIXct(rc_segundos$Time, format = "%m/%d/%Y %I:%M:%S %p"),"%Y/%m/%d %H:%M:%S")
```

```{r}
#limpieza de variables
actividad_diaria <- subset(actividad_diaria,
                           select = -c(TrackerDistance, LoggedActivitiesDistance, VeryActiveDistance,
                                       ModeratelyActiveDistance, LightActiveDistance, SedentaryActiveDistance,
                                       VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, ActivityDate))
sueno_diario <- subset(sueno_diario,
                       select = -c(SleepDay))
peso_eventual <- subset(peso_eventual,
                        select = -c(WeightPounds, Fat, IsManualReport, LogId))
```

```{r}
#revisión de Identificadores e Intersección
length(unique(actividad_diaria$Id)) #33 personas
length(unique(sueno_diario$Id)) #24 personas (subconjunto de las 33)
length(unique(rc_segundos$Id)) #14 personas (subconjunto de las 33 y 24)
length(unique(peso_eventual$Id)) #8 personas (subconjunto de las 33, 24 y 14)

ids_comunes <- intersect(actividad_diaria$Id, sueno_diario$Id)
length(ids_comunes)
```


```{r}
#Exportar los archivos limpios
write.csv(actividad_diaria, "actividad_diaria.csv", row.names = FALSE)
write.csv(sueno_diario, "sueno_diario.csv", row.names = FALSE)
write.csv(peso_eventual, "peso_eventual.csv", row.names = FALSE)
write.csv(rc_segundos, "rc_segundos.csv", row.names = FALSE)
```

